import type { AppProps } from 'next/app'
import Head from 'next/head'
import Box from '~/primitive/Box'
import Footer from '~/components/Footer'
import Navbar from '~/components/Navbar'
import TopBar from '~/components/TopBar'
import CartContext from '~/contexts/cartContext'
import { styled } from '~/theme'
import '../styles/globals.css'

const Container = styled(Box, {
  position: 'relative',
  display: 'flex',
  paddingVertical: '$50',
  paddingHorizontal: '5%',

  '@sm': {
    paddingHorizontal: '10%',
  },
  '@md': {
    paddingHorizontal: '15%',
  },
  '@lg': {
    paddingHorizontal: '20%',
  },
})

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>e-commerce NSCPB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <CartContext>
        <Navbar />

        <Container>
          <Component {...pageProps} />
        </Container>
      </CartContext>

      <Footer />
    </>
  )
}

export default App 