import type { AppProps } from 'next/app'
import Head from 'next/head'
import Box from '~/primitive/Box'
import Footer from '~/components/Footer'
import Header from '~/components/Header'
import CartContext from '~/contexts/cartContext'
import { styled } from '~/theme'
import '../styles/globals.css'

const Container = styled(Box, {
  position: 'relative',
  paddingVertical: '$50',
  paddingTop: '200px',
  paddingHorizontal: '5%',

  '@sm': {
    paddingHorizontal: '10%',
  },
  '@md': {
    paddingHorizontal: '15%',
  },
  '@lg': {
    paddingHorizontal: '20%',
  },
})

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Núcleo SCP Batalha</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <CartContext>
        <Header />

        <Container>
          <Component {...pageProps} />
        </Container>
      </CartContext>

      <Footer />
    </>
  )
}

export default App
